### ISSUE TITLE
Possible features

### ISSUE THREAD

**Issue by luctst** [Kvin3324/todoApp#1]
Hey  👋

J'ai checké un peu le rendu c'est cool.

Par contre ce que tu peux ajouter comme feature c'est le fait de checker si une task n'est pas déja rentrée dans ce cas ça sert à rien de l'ajouter ça fait des doublons pour rien. Aussi pourquoi pas la possibilité d'éditer une task en cours ? De maniére à quand tu cliques dessus ça devient un input et tu peux en changer la valeur ?

Voila la bise

**Comment by Kvin3324** [comment]
Yes, merci @luctst pour tes suggestions, je vais en prendre note (ou pas), j'ai aussi d'autres petites features à faire avant ça.

Thanks. 🙏
